name    'mayflower-prosody'
version '0.1.3'
source 'https://github.com/Mayflower/puppet-prosody'
author 'Mayflower'
license 'Apache License, Version 2.0'
summary 'A simple Puppet module for managing the Prosody Jabber server'
description 'This module supports most configuration options and installing community modules'
project_page 'https://github.com/Mayflower/puppet-prosody'
dependency 'puppetlabs/stdlib', '>= 3.2.0'

